//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8
        ///131
        ///91
        ///35
        ///47
        ///116
        ///105
        ///121
        ///56
        ///62
        ///94
        ///72
        ///13
        ///82
        ///156
        ///102
        ///12
        ///59
        ///31
        ///138
        ///46
        ///120
        ///7
        ///127
        ///126
        ///111
        ///2
        ///123
        ///22
        ///69
        ///18
        ///157
        ///75
        ///149
        ///88
        ///81
        ///23
        ///98
        ///132
        ///1
        ///63
        ///142
        ///37
        ///133
        ///61
        ///112
        ///122
        ///128
        ///155
        ///145
        ///139
        ///66
        ///42
        ///134
        ///24
        ///60
        ///9
        ///28
        ///17
        ///29
        ///101
        ///148
        ///96
        ///68
        ///25
        ///19
        ///6
        ///67
        ///113
        ///55
        ///40
        ///135
        ///97
        ///79
        ///48
        ///159
        ///14
        ///43
        ///86
        ///36
        ///41
        ///85
        ///87
        ///119
        ///30
        ///108
        ///80
        ///152
        ///158
        ///151
        ///32
        ///78
        ///150
        ///95
        ///3
        ///52
        ///49.
        /// </summary>
        internal static string Day10Adapter {
            get {
                return ResourceManager.GetString("Day10Adapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1782
        ///1344
        ///1974
        ///1874
        ///1800
        ///1973
        ///1416
        ///1952
        ///1982
        ///1506
        ///1642
        ///1514
        ///1978
        ///1895
        ///1747
        ///1564
        ///1398
        ///1683
        ///1886
        ///1492
        ///1629
        ///1433
        ///295
        ///1793
        ///1740
        ///1852
        ///1697
        ///1471
        ///1361
        ///1751
        ///1426
        ///2004
        ///1763
        ///1663
        ///1742
        ///1666
        ///1733
        ///1880
        ///1600
        ///1723
        ///1478
        ///1912
        ///1820
        ///1615
        ///1875
        ///1547
        ///1554
        ///752
        ///1905
        ///1368
        ///954
        ///1425
        ///1391
        ///691
        ///1835
        ///744
        ///1850
        ///1713
        ///1995
        ///1926
        ///1817
        ///1774
        ///1986
        ///2010
        ///1427
        ///1609
        ///1927
        ///1362
        ///1420
        ///1722
        ///1590
        ///1925
        ///1617
        ///1434
        ///1826
        ///1636
        ///1687
        ///1946
        ///704
        ///1797
        ///1517
        ///1801
        ///1865
        ///1963
        ///1828
        ///1829
        ///19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1Expenses {
            get {
                return ResourceManager.GetString("Day1Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-8 n: dpwpmhknmnlglhjtrbpx
        ///11-12 n: frpknnndpntnncnnnnn
        ///4-8 t: tmttdtnttkr
        ///12-18 v: vvvvvvvqvvvvvqvvgf
        ///3-4 c: cccc
        ///17-18 z: zzzzzzzzdzzzzzzgzr
        ///5-6 l: llltzl
        ///4-5 g: fzfng
        ///3-6 b: bjsbbxbb
        ///4-5 b: dbbbl
        ///1-4 t: tttcrt
        ///8-11 t: tttwtttwttn
        ///16-17 m: mmmmmmmmmmmmmmmbp
        ///8-11 f: fffffffqfmzfff
        ///10-12 n: nnnnnnnnnncvnnnf
        ///5-15 b: ztmcfqsrbvbbbqbxw
        ///12-13 m: mmmmmmrwmnmmr
        ///5-6 d: sddddznddddkzdbpdv
        ///14-15 l: lsllllskllllllllll
        ///3-4 z: zvrz
        ///2-8 h: fthhhqhghhtf
        ///2-4 x: xhtxsp
        ///6-10 q: qqlxqcvqwqqx
        ///1-3 q: qq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2Passwords {
            get {
                return ResourceManager.GetString("Day2Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .......#................#......
        ///...#.#.....#.##.....#..#.......
        ///..#..#.#......#.#.#............
        ///....#...#...##.....#..#.....#..
        ///....#.......#.##......#...#..#.
        ///...............#.#.#.....#..#..
        ///...##...#...#..##.###...##.....
        ///##..#.#...##.....#.#..........#
        ///.#....#..#..#......#....#....#.
        ///...........................#...
        ///..........#.......#..#.....#.#.
        ///..#.......###..#.#.......#.#...
        ///....#..#....#....#..........#..
        ///..##..#.......#.#...#..........
        ///.....#.......#.....#....#......
        ///..........##..#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3Trees {
            get {
                return ResourceManager.GetString("Day3Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iyr:2010 ecl:gry hgt:181cm
        ///pid:591597745 byr:1920 hcl:#6b5442 eyr:2029 cid:123
        ///
        ///cid:223 byr:1927
        ///hgt:177cm hcl:#602927 iyr:2016 pid:404183620
        ///ecl:amb
        ///eyr:2020
        ///
        ///byr:1998
        ///ecl:hzl
        ///cid:178 hcl:#a97842 iyr:2014 hgt:166cm pid:594143498 eyr:2030
        ///
        ///ecl:hzl
        ///pid:795349208 iyr:2018
        ///eyr:2024 hcl:#de745c hgt:157cm
        ///
        ///hgt:159cm pid:364060467 eyr:2025 byr:1978 iyr:2018 cid:117
        ///ecl:hzl
        ///hcl:#18171d
        ///
        ///hcl:#cfa07d
        ///ecl:amb iyr:2012
        ///hgt:182cm cid:338
        ///eyr:2020
        ///pid:374679609 byr:1925
        ///
        ///eyr:2021 byr:1981
        ///hcl: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4Passport {
            get {
                return ResourceManager.GetString("Day4Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBFFFFBRLL
        ///BFBBBBFLLL
        ///FBBBFBFLLR
        ///BFBBBFBLRR
        ///FBBFFBFLRR
        ///FFBFFBFRRR
        ///FBFBBBBLLL
        ///BFFBFFFRLR
        ///BFFBFFFRLL
        ///BFBBFBFRRL
        ///FBFFFFBLRR
        ///BBFFBFBLLR
        ///BBFBFFBRLR
        ///BFBFBFFRLR
        ///FBFFBFBRRL
        ///BFFFFBFRLR
        ///FFBBBBBRLR
        ///BFFFBFBLLR
        ///FBBBBBBRLL
        ///FBBFBFBRRL
        ///FBFBFBFLRL
        ///FFBFBBFRLL
        ///BFBFFBFRRL
        ///FBBBBFBLLR
        ///FFBBFBFLRR
        ///BFBFBBFRRL
        ///FBFFFBBLLR
        ///FBBFFBFRRR
        ///FFFBFBBLRL
        ///FBBBBFBRRL
        ///BFBFBBFLRL
        ///BBFFBFBLRL
        ///BBFFFFFLRL
        ///BBFBBFFRLR
        ///FFBFBBBRRL
        ///FBFFFFFRLR
        ///FFFBBFFLRR
        ///BFFFBFFLRL
        ///BFBFFFBRLR
        ///BBFBFBFLRR
        ///FBBBBFFRRR
        ///FBFFFBFRLL
        ///FBFFFFFL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5Boarding {
            get {
                return ResourceManager.GetString("Day5Boarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zvxc
        ///dv
        ///vh
        ///xv
        ///jvem
        ///
        ///mxfhdeyikljnz
        ///vwzbjmsrgq
        ///
        ///vbtjnh
        ///vhejnbti
        ///vthnjb
        ///tsbhjnv
        ///
        ///cbjemdvp
        ///jdvuylp
        ///ofpjaqgsrxvdn
        ///dzvpbj
        ///vbktpdj
        ///
        ///knyvdhsemu
        ///sdyumkgvh
        ///muyvdskh
        ///syhkuvmd
        ///dvmykshu
        ///
        ///rmantzovbsuxiljkchfgdqew
        ///vficzosgwlmrdtqkueajbnxh
        ///davqlntibxhojesrkugpzmwfc
        ///
        ///ifdmgrcve
        ///bkqal
        ///gxcwvt
        ///
        ///xeiokblasch
        ///toxjlsbnciha
        ///sovycihlabx
        ///ximhylocabs
        ///hixsolabc
        ///
        ///iyfkvmpolta
        ///thpqodzifxc
        ///
        ///iexunoyhwv
        ///ovweiyuhxn
        ///uhojnvyxeiw
        ///
        ///vbncamhzojtqrlpse
        ///wujapcidzx
        ///zxjiuacwkgfdp
        ///
        ///bygewhzsnqvxaoc
        ///sngqv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day6Customs {
            get {
                return ResourceManager.GetString("Day6Customs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear maroon bags contain 1 dull lavender bag.
        ///wavy turquoise bags contain 4 vibrant magenta bags, 4 light violet bags, 5 bright gold bags, 2 faded black bags.
        ///wavy beige bags contain 3 plaid magenta bags, 3 wavy lime bags, 2 clear turquoise bags, 3 muted cyan bags.
        ///mirrored black bags contain 1 plaid red bag, 3 light gold bags, 3 wavy violet bags.
        ///vibrant fuchsia bags contain 2 dark lime bags, 2 mirrored black bags, 2 light magenta bags, 2 drab chartreuse bags.
        ///vibrant plum bags contain 4 dim cyan bag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day7Haversacks {
            get {
                return ResourceManager.GetString("Day7Haversacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acc +28
        ///jmp +481
        ///nop +87
        ///acc -10
        ///acc +21
        ///jmp +548
        ///jmp +250
        ///acc -9
        ///acc +19
        ///acc -3
        ///nop +85
        ///jmp +84
        ///acc +43
        ///acc +34
        ///acc -5
        ///jmp +602
        ///nop +416
        ///acc +19
        ///acc +46
        ///acc +33
        ///jmp +133
        ///acc -3
        ///acc +5
        ///jmp +143
        ///nop -18
        ///acc +50
        ///acc +0
        ///acc -6
        ///jmp +243
        ///acc +11
        ///acc -18
        ///jmp +501
        ///acc +45
        ///jmp +449
        ///acc +0
        ///acc -10
        ///acc +20
        ///nop +516
        ///jmp +544
        ///jmp +551
        ///nop +59
        ///nop +247
        ///acc -1
        ///jmp +589
        ///acc +41
        ///jmp +457
        ///jmp +102
        ///acc +22
        ///jmp +195
        ///acc +30
        ///jmp -38
        ///acc +21
        ///nop -3
        ///jmp +466
        ///acc +47
        ///acc +4
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day8Handheld {
            get {
                return ResourceManager.GetString("Day8Handheld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///48
        ///30
        ///21
        ///18
        ///50
        ///9
        ///37
        ///5
        ///31
        ///17
        ///39
        ///14
        ///45
        ///27
        ///23
        ///2
        ///4
        ///19
        ///35
        ///10
        ///32
        ///33
        ///28
        ///7
        ///34
        ///11
        ///6
        ///8
        ///12
        ///54
        ///13
        ///9
        ///15
        ///16
        ///60
        ///64
        ///17
        ///14
        ///18
        ///20
        ///23
        ///24
        ///25
        ///19
        ///21
        ///26
        ///22
        ///27
        ///46
        ///28
        ///29
        ///30
        ///31
        ///32
        ///38
        ///33
        ///37
        ///45
        ///63
        ///34
        ///35
        ///39
        ///51
        ///40
        ///41
        ///43
        ///60
        ///44
        ///47
        ///52
        ///58
        ///62
        ///55
        ///57
        ///59
        ///61
        ///64
        ///100
        ///65
        ///95
        ///73
        ///71
        ///69
        ///103
        ///74
        ///82
        ///83
        ///108
        ///147
        ///160
        ///87
        ///117
        ///91
        ///112
        ///107
        ///176
        ///114
        ///116
        ///148
        ///120
        ///125
        ///133
        ///190
        ///134
        ///152
        ///205
        ///183
        ///156
        ///216
        ///199
        ///202
        ///174
        ///211
        ///219
        ///194
        ///178
        ///198
        ///203
        ///223
        ///221
        ///354        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day9Encoding {
            get {
                return ResourceManager.GetString("Day9Encoding", resourceCulture);
            }
        }
    }
}
