//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1782
        ///1344
        ///1974
        ///1874
        ///1800
        ///1973
        ///1416
        ///1952
        ///1982
        ///1506
        ///1642
        ///1514
        ///1978
        ///1895
        ///1747
        ///1564
        ///1398
        ///1683
        ///1886
        ///1492
        ///1629
        ///1433
        ///295
        ///1793
        ///1740
        ///1852
        ///1697
        ///1471
        ///1361
        ///1751
        ///1426
        ///2004
        ///1763
        ///1663
        ///1742
        ///1666
        ///1733
        ///1880
        ///1600
        ///1723
        ///1478
        ///1912
        ///1820
        ///1615
        ///1875
        ///1547
        ///1554
        ///752
        ///1905
        ///1368
        ///954
        ///1425
        ///1391
        ///691
        ///1835
        ///744
        ///1850
        ///1713
        ///1995
        ///1926
        ///1817
        ///1774
        ///1986
        ///2010
        ///1427
        ///1609
        ///1927
        ///1362
        ///1420
        ///1722
        ///1590
        ///1925
        ///1617
        ///1434
        ///1826
        ///1636
        ///1687
        ///1946
        ///704
        ///1797
        ///1517
        ///1801
        ///1865
        ///1963
        ///1828
        ///1829
        ///19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1Expenses {
            get {
                return ResourceManager.GetString("Day1Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-8 n: dpwpmhknmnlglhjtrbpx
        ///11-12 n: frpknnndpntnncnnnnn
        ///4-8 t: tmttdtnttkr
        ///12-18 v: vvvvvvvqvvvvvqvvgf
        ///3-4 c: cccc
        ///17-18 z: zzzzzzzzdzzzzzzgzr
        ///5-6 l: llltzl
        ///4-5 g: fzfng
        ///3-6 b: bjsbbxbb
        ///4-5 b: dbbbl
        ///1-4 t: tttcrt
        ///8-11 t: tttwtttwttn
        ///16-17 m: mmmmmmmmmmmmmmmbp
        ///8-11 f: fffffffqfmzfff
        ///10-12 n: nnnnnnnnnncvnnnf
        ///5-15 b: ztmcfqsrbvbbbqbxw
        ///12-13 m: mmmmmmrwmnmmr
        ///5-6 d: sddddznddddkzdbpdv
        ///14-15 l: lsllllskllllllllll
        ///3-4 z: zvrz
        ///2-8 h: fthhhqhghhtf
        ///2-4 x: xhtxsp
        ///6-10 q: qqlxqcvqwqqx
        ///1-3 q: qq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2Passwords {
            get {
                return ResourceManager.GetString("Day2Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .......#................#......
        ///...#.#.....#.##.....#..#.......
        ///..#..#.#......#.#.#............
        ///....#...#...##.....#..#.....#..
        ///....#.......#.##......#...#..#.
        ///...............#.#.#.....#..#..
        ///...##...#...#..##.###...##.....
        ///##..#.#...##.....#.#..........#
        ///.#....#..#..#......#....#....#.
        ///...........................#...
        ///..........#.......#..#.....#.#.
        ///..#.......###..#.#.......#.#...
        ///....#..#....#....#..........#..
        ///..##..#.......#.#...#..........
        ///.....#.......#.....#....#......
        ///..........##..#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3Trees {
            get {
                return ResourceManager.GetString("Day3Trees", resourceCulture);
            }
        }
    }
}
